### ISSUE TITLE
可以透露一下这个svg是怎么制作的吗

### ISSUE THREAD

**Issue by neewbee** [ant-motion/ant-design-pro-landing-page#1]
具体流程是怎么样？用到了什么工具？谢谢

**Comment by jljsj33** [comment]
目前是我手动替换 g 标签的，后续会考虑增加一个自动完成图层动画处理组件，不过最好不要用 svg ，，渲染负担太大， 坑也很多，比如在 safari 下获取不到样式的 transform，最好还是用图片。。。

**Comment by neewbee** [comment]
这个svg本身是由设计师用其他工具生成然后导出的么？

**Comment by jljsj33** [comment]
svg 图片拖到 vs code  会转成代码的，，，或者直接在sketch 里 copy svg code ,,, 方法有很多种。。。

**Comment by jljsj33** [comment]
直接拖到 chrome 里右击查看源码也可以。。。
